name: Deploy AWS EC2 Auto Stop

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  LAMBDA_FUNCTION_NAME: ec2-auto-stop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3️⃣ Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # -------------------------------
      # 🌍 Terraform
      # -------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      # -------------------------------
      # 📦 Lambda Packaging
      # -------------------------------
      - name: Package Lambda
        run: |
          cd lambda
          mkdir package

          pip install -r requirements.txt -t package/

          cp auto_stop.py package/

          cd package
          zip -r ../function.zip .

      # -------------------------------
      # 🚀 Deploy Lambda
      # -------------------------------
      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --zip-file fileb://lambda/function.zip